apiVersion: apps/v1
kind: Deployment
metadata:
  name: shareable-backend-deployment
  labels:
    app: shareable-backend
    version: latest
    context: front-end
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shareable-backend
      version: latest
      context: front-end
  template:
    metadata:
      labels:
        app: shareable-backend
        version: latest
        context: front-end
    spec:
      containers:
        - name: shareable-backend
          image: localhost:5000/back-end/latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: shareable-backend-service
  labels:
    app: shareable-backend
    version: latest
    context: front-end
spec:
  ports:
    - port: 3080
      nodePort: 30080
      targetPort: 80
      protocol: TCP
  selector:
    app: blossom-studio
  type: LoadBalancer

